export const CIIU_ACTIVIDAD: Record<string, string> = {
  "111": "Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas.",
  "112": "Cultivo de arroz.",
  "113": "Cultivo de hortalizas, raíces y tubérculos.",
  "114": "Cultivo de tabaco.",
  "115": "Cultivo de plantas textiles.",
  "119": "Otros cultivos transitorios n.c.p.",
  "121": "Cultivo de frutas tropicales y subtropicales.",
  "122": "Cultivo de plátano y banano.",
  "123": "Cultivo de café.",
  "124": "Cultivo de caña de azúcar.",
  "125": "Cultivo de flor de corte.",
  "126": "Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos.",
  "127": "Cultivo de plantas con las que se preparan bebidas.",
  "128": "Cultivo de especias y de plantas aromáticas y medicinales.",
  "129": "Otros cultivos permanentes n.c.p.",
  "130": "Propagación de plantas (actividades de los viveros, excepto viveros forestales).",
  "141": "Cría de ganado bovino y bufalino.",
  "142": "Cría de caballos y otros equinos.",
  "143": "Cría de ovejas y cabras.",
  "144": "Cría de ganado porcino.",
  "145": "Cría de aves de corral.",
  "149": "Cría de otros animales n.c.p.",
  "150": "Explotación mixta (agrícola y pecuaria).",
  "161": "Actividades de apoyo a la agricultura.",
  "162": "Actividades de apoyo a la ganadería.",
  "163": "Actividades posteriores a la cosecha.",
  "164": "Tratamiento de semillas para propagación.",
  "170": "Caza ordinaria y mediante trampas y actividades de servicios conexas.",
  "210": "Silvicultura y otras actividades forestales.",
  "220": "Extracción de madera.",
  "230": "Recolección de productos forestales diferentes a la madera.",
  "240": "Servicios de apoyo a la silvicultura.",
  "311": "Pesca marítima.",
  "312": "Pesca de agua dulce.",
  "321": "Acuicultura marítima.",
  "322": "Acuicultura de agua dulce.",
  "510": "Extracción de hulla (carbón de piedra).",
  "520": "Extracción de carbón lignito.",
  "610": "Extracción de petróleo crudo.",
  "620": "Extracción de gas natural.",
  "710": "Extracción de minerales de hierro.",
  "721": "Extracción de minerales de uranio y de torio.",
  "722": "Extracción de oro y otros metales preciosos.",
  "723": "Extracción de minerales de níquel.",
  "729": "Extracción de otros minerales metalíferos no ferrosos n.c.p.",
  "811": "Extracción de piedra, arena, arcillas comunes, yeso y anhidrita.",
  "812": "Extracción de arcillas de uso industrial, caliza, caolín y bentonitas.",
  "820": "Extracción de esmeraldas, piedras preciosas y semipreciosas.",
  "891": "Extracción de minerales para la fabricación de abonos y productos químicos.",
  "892": "Extracción de halita (sal).",
  "899": "Extracción de otros minerales no metálicos n.c.p.",
  "910": "Actividades de apoyo para la extracción de petróleo y de gas natural.",
  "990": "Actividades de apoyo para otras actividades de explotación de minas y canteras.",
  "1011": "Procesamiento y conservación de carne y productos cárnicos.",
  "1012": "Procesamiento y conservación de pescados, crustáceos y moluscos.",
  "1020": "Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos.",
  "1030": "Elaboración de aceites y grasas de origen vegetal y animal.",
  "1040": "Elaboración de productos lácteos.",
  "1051": "Elaboración de productos de molinería.",
  "1052": "Elaboración de almidones y productos derivados del almidón.",
  "1061": "Trilla de café.",
  "1062": "Descafeinado, tostión y molienda del café.",
  "1063": "Otros derivados del café.",
  "1071": "Elaboración y refinación de azúcar.",
  "1072": "Elaboración de panela.",
  "1081": "Elaboración de productos de panadería.",
  "1082": "Elaboración de cacao, chocolate y productos de confitería.",
  "1083": "Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares.",
  "1084": "Elaboración de comidas y platos preparados.",
  "1089": "Elaboración de otros productos alimenticios n.c.p.",
  "1090": "Elaboración de alimentos preparados para animales.",
  "1101": "Destilación, rectificación y mezcla de bebidas alcohólicas.",
  "1102": "Elaboración de bebidas fermentadas no destiladas.",
  "1103": "Producción de malta, elaboración de cervezas y otras bebidas malteadas.",
  "1104": "Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas.",
  "1200": "Elaboración de productos de tabaco.",
  "1311": "Preparación e hilatura de fibras textiles.",
  "1312": "Tejeduría de productos textiles.",
  "1313": "Acabado de productos textiles.",
  "1391": "Fabricación de tejidos de punto y ganchillo.",
  "1392": "Confección de artículos con materiales textiles, excepto prendas de vestir.",
  "1393": "Fabricación de tapetes y alfombras para pisos.",
  "1394": "Fabricación de cuerdas, cordeles, cables, bramantes y redes.",
  "1399": "Fabricación de otros artículos textiles n.c.p.",
  "1410": "Confección de prendas de vestir, excepto prendas de piel.",
  "1420": "Fabricación de artículos de piel.",
  "1430": "Fabricación de artículos de punto y ganchillo.",
  "1511": "Curtido y recurtido de cueros; recurtido y teñido de pieles.",
  "1512": "Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería.",
  "1513": "Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales.",
  "1521": "Fabricación de calzado de cuero y piel, con cualquier tipo de suela.",
  "1522": "Fabricación de otros tipos de calzado, excepto calzado de cuero y piel.",
  "1523": "Fabricación de partes del calzado.",
  "1610": "Aserrado, acepillado e impregnación de la madera.",
  "1620": "Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles.",
  "1630": "Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción.",
  "1640": "Fabricación de recipientes de madera.",
  "1690": "Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería.",
  "1701": "Fabricación de pulpas (pastas) celulósicas; papel y cartón.",
  "1702": "Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón.",
  "1709": "Fabricación de otros artículos de papel y cartón.",
  "1811": "Actividades de impresión.",
  "1812": "Actividades de servicios relacionados con la impresión.",
  "1820": "Producción de copias a partir de grabaciones originales.",
  "1910": "Fabricación de productos de hornos de coque.",
  "1921": "Fabricación de productos de la refinación del petróleo.",
  "1922": "Actividad de mezcla de combustibles.",
  "2011": "Fabricación de sustancias y productos químicos básicos.",
  "2012": "Fabricación de abonos y compuestos inorgánicos nitrogenados.",
  "2013": "Fabricación de plásticos en formas primarias.",
  "2014": "Fabricación de caucho sintético en formas primarias.",
  "2021": "Fabricación de plaguicidas y otros productos químicos de uso agropecuario.",
  "2022": "Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas.",
  "2023": "Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador.",
  "2029": "Fabricación de otros productos químicos n.c.p.",
  "2030": "Fabricación de fibras sintéticas y artificiales.",
  "2100": "Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico.",
  "2211": "Fabricación de llantas y neumáticos de caucho.",
  "2212": "Reencauche de llantas usadas.",
  "2219": "Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.",
  "2221": "Fabricación de formas básicas de plástico.",
  "2229": "Fabricación de artículos de plástico n.c.p.",
  "2310": "Fabricación de vidrio y productos de vidrio.",
  "2391": "Fabricación de productos refractarios.",
  "2392": "Fabricación de materiales de arcilla para la construcción.",
  "2393": "Fabricación de otros productos de cerámica y porcelana.",
  "2394": "Fabricación de cemento, cal y yeso.",
  "2395": "Fabricación de artículos de hormigón, cemento y yeso.",
  "2396": "Corte, tallado y acabado de la piedra.",
  "2399": "Fabricación de otros productos minerales no metálicos n.c.p.",
  "2410": "Industrias básicas de hierro y de acero.",
  "2421": "Industrias básicas de metales preciosos.",
  "2429": "Industrias básicas de otros metales no ferrosos.",
  "2431": "Fundición de hierro y de acero.",
  "2432": "Fundición de metales no ferrosos.",
  "2511": "Fabricación de productos metálicos para uso estructural.",
  "2512": "Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías.",
  "2513": "Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central.",
  "2520": "Fabricación de armas y municiones.",
  "2591": "Forja, prensado, estampado y laminado de metal; pulvimetalurgia.",
  "2592": "Tratamiento y revestimiento de metales; mecanizado.",
  "2593": "Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería.",
  "2599": "Fabricación de otros productos elaborados de metal n.c.p.",
  "2610": "Fabricación de componentes y tableros electrónicos.",
  "2620": "Fabricación de computadoras y de equipo periférico.",
  "2630": "Fabricación de equipos de comunicación.",
  "2640": "Fabricación de aparatos electrónicos de consumo.",
  "2651": "Fabricación de equipo de medición, prueba, navegación y control",
  "2652": "Fabricación de relojes",
  "2660": "Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico",
  "2670": "Fabricación de instrumentos ópticos y equipo fotográfico",
  "2680": "Fabricación de medios magnéticos y ópticos para almacenamiento de datos",
  "2711": "Fabricación de motores, generadores y transformadores eléctricos",
  "2712": "Fabricación de aparatos de distribución y control de la energía eléctrica",
  "2720": "Fabricación de pilas, baterías y acumuladores eléctricos",
  "2731": "Fabricación de hilos y cables eléctricos y de fibra óptica",
  "2732": "Fabricación de dispositivos de cableado",
  "2740": "Fabricación de equipos eléctricos de iluminación",
  "2750": "Fabricación de aparatos de uso doméstico",
  "2790": "Fabricación de otros tipos de equipo eléctrico n.c.p.",
  "2811": "Fabricación de motores, turbinas, y partes para motores de combustión interna.",
  "2812": "Fabricación de equipos de potencia hidráulica y neumática.",
  "2813": "Fabricación de otras bombas, compresores, grifos y válvulas.",
  "2814": "Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión.",
  "2815": "Fabricación de hornos, hogares y quemadores industriales.",
  "2816": "Fabricación de equipo de elevación y manipulación.",
  "2817": "Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico).",
  "2818": "Fabricación de herramientas manuales con motor.",
  "2819": "Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.",
  "2821": "Fabricación de maquinaria agropecuaria y forestal.",
  "2822": "Fabricación de máquinas formadoras de metal y de máquinas herramienta.",
  "2823": "Fabricación de maquinaria para la metalurgia.",
  "2824": "Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción.",
  "2825": "Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco.",
  "2826": "Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros.",
  "2829": "Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.",
  "2910": "Fabricación de vehículos automotores y sus motores.",
  "2920": "Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques.",
  "2930": "Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores.",
  "3011": "Construcción de barcos y de estructuras flotantes.",
  "3012": "Construcción de embarcaciones de recreo y deporte.",
  "3020": "Fabricación de locomotoras y de material rodante para ferrocarriles.",
  "3030": "Fabricación de aeronaves, naves espaciales y de maquinaria conexa.",
  "3040": "Fabricación de vehículos militares de combate.",
  "3091": "Fabricación de motocicletas.",
  "3092": "Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad.",
  "3099": "Fabricación de otros tipos de equipo de transporte n.c.p.",
  "3110": "Fabricación de muebles.",
  "3120": "Fabricación de colchones y somieres.",
  "3210": "Fabricación de joyas, bisutería y artículos conexos.",
  "3220": "Fabricación de instrumentos musicales.",
  "3230": "Fabricación de artículos y equipo para la práctica del deporte.",
  "3240": "Fabricación de juegos, juguetes y rompecabezas.",
  "3250": "Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario).",
  "3290": "Otras industrias manufactureras n.c.p.",
  "3311": "Mantenimiento y reparación especializado de productos elaborados en metal.",
  "3312": "Mantenimiento y reparación especializado de maquinaria y equipo.",
  "3313": "Mantenimiento y reparación especializado de equipo electrónico y óptico.",
  "3314": "Mantenimiento y reparación especializado de equipo eléctrico.",
  "3315": "Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas.",
  "3319": "Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.",
  "3320": "Instalación especializada de maquinaria y equipo industrial.",
  "3511": "Generación de energía eléctrica.",
  "3512": "Transmisión de energía eléctrica.",
  "3513": "Distribución de energía eléctrica.",
  "3514": "Comercialización de energía eléctrica",
  "3520": "Producción de gas; distribución de combu.stibles gaseosos por tuberías.",
  "3530": "Suministro de vapor y aire acondicionado.",
  "3600": "Captación, tratamiento y distribución de agua.",
  "3700": "Evacuación y tratamiento de aguas residuales.",
  "3811": "Recolección de desechos no peligrosos.",
  "3812": "Recolección de desechos peligrosos.",
  "3821": "Tratamiento y disposición de desechos no peligrosos.",
  "3822": "Tratamiento y disposición de desechos peligrosos.",
  "3830": "Recuperación de materiales.",
  "3900": "Actividades de saneamiento ambiental y otros servicios de gestión de desechos.",
  "4111": "Construcción de edificios residenciales.",
  "4112": "Construcción de edificios no residenciales.",
  "4210": "Construcción de carreteras y vías de ferrocarril.",
  "4220": "Construcción de proyectos de servicio público.",
  "4290": "Construcción de otras obras de ingeniería civil.",
  "4311": "Demolición.",
  "4312": "Preparación del terreno.",
  "4321": "Instalaciones eléctricas.",
  "4322": "Instalaciones de fontanería, calefacción y aire acondicionado.",
  "4329": "Otras instalaciones especializadas.",
  "4330": "Terminación y acabado de edificios y obras de ingeniería civil.",
  "4390": "Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil.",
  "4511": "Comercio de vehículos automotores nuevos.",
  "4512": "Comercio de vehículos automotores usados.",
  "4520": "Mantenimiento y reparación de vehículos automotores.",
  "4530": "Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores.",
  "4541": "Comercio de motocicletas y de sus partes, piezas y accesorios.",
  "4542": "Mantenimiento y reparación de motocicletas y de sus partes y piezas.",
  "4610": "Comercio al por mayor a cambio de una retribución o por contrata.",
  "4620": "Comercio al por mayor de materias primas agropecuarias; animales vivos.",
  "4631": "Comercio al por mayor de productos alimenticios.",
  "4632": "Comercio al por mayor de bebidas y tabaco.",
  "4641": "Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico.",
  "4642": "Comercio al por mayor de prendas de vestir.",
  "4643": "Comercio al por mayor de calzado.",
  "4644": "Comercio al por mayor de aparatos y equipo de uso doméstico.",
  "4645": "Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador.",
  "4649": "Comercio al por mayor de otros utensilios domésticos n.c.p.",
  "4651": "Comercio al por mayor de computadores, equipo periférico y programas de informática.",
  "4652": "Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones.",
  "4653": "Comercio al por mayor de maquinaria y equipo agropecuarios.",
  "4659": "Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.",
  "4661": "Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos.",
  "4662": "Comercio al por mayor de metales y productos metalíferos.",
  "4663": "Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción.",
  "4664": "Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario.",
  "4665": "Comercio al por mayor de desperdicios, desechos y chatarra.",
  "4669": "Comercio al por mayor de otros productos n.c.p.",
  "4690": "Comercio al por mayor no especializado.",
  "4711": "Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco.",
  "4719": "Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas y tabaco.",
  "4721": "Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados.",
  "4722": "Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados.",
  "4723": "Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados.",
  "4724": "Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados.",
  "4729": "Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados.",
  "4731": "Comercio al por menor de combustible para automotores.",
  "4732": "Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores.",
  "4741": "Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados.",
  "4742": "Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados.",
  "4751": "Comercio al por menor de productos textiles en establecimientos especializados.",
  "4752": "Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados.",
  "4753": "Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos en establecimientos especializados.",
  "4754": "Comercio al por menor de electrodomésticos y gasodomésticos de uso doméstico, muebles y equipos de iluminación.",
  "4755": "Comercio al por menor de artículos y utensilios de uso doméstico.",
  "4759": "Comercio al por menor de otros artículos domésticos en establecimientos especializados.",
  "4761": "Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados.",
  "4762": "Comercio al por menor de artículos deportivos, en establecimientos especializados.",
  "4769": "Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados.",
  "4771": "Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados.",
  "4772": "Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados.",
  "4773": "Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados.",
  "4774": "Comercio al por menor de otros productos nuevos en establecimientos especializados.",
  "4775": "Comercio al por menor de artículos de segunda mano.",
  "4781": "Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles.",
  "4782": "Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles.",
  "4789": "Comercio al por menor de otros productos en puestos de venta móviles.",
  "4791": "Comercio al por menor realizado a través de Internet.",
  "4792": "Comercio al por menor realizado a través de casas de venta o por correo.",
  "4799": "Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados.",
  "4911": "Transporte férreo de pasajeros.",
  "4912": "Transporte férreo de carga.",
  "4921": "Transporte de pasajeros.",
  "4922": "Transporte mixto.",
  "4923": "Transporte de carga por carretera.",
  "4930": "Transporte por tuberías.",
  "5011": "Transporte de pasajeros marítimo y de cabotaje.",
  "5012": "Transporte de carga marítimo y de cabotaje.",
  "5021": "Transporte fluvial de pasajeros.",
  "5022": "Transporte fluvial de carga.",
  "5111": "Transporte aéreo nacional de pasajeros.",
  "5112": "Transporte aéreo internacional de pasajeros.",
  "5121": "Transporte aéreo nacional de carga.",
  "5122": "Transporte aéreo internacional de carga.",
  "5210": "Almacenamiento y depósito",
  "5221": "Actividades de estaciones, vías y servicios complementarios para el transporte terrestre.",
  "5222": "Actividades de puertos y servicios complementarios para el transporte acuático.",
  "5223": "Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo",
  "5224": "Manipulación de carga",
  "5229": "Otras actividades complementarias al transporte.",
  "5310": "Actividades postales nacionales.",
  "5320": "Actividades de mensajería.",
  "5511": "Alojamiento en hoteles.",
  "5512": "Alojamiento en apartahoteles.",
  "5513": "Alojamiento en centros vacacionales",
  "5514": "Alojamiento rural.",
  "5519": "Otros tipos de alojamientos para visitantes.",
  "5520": "Actividades de zonas de camping y parques para vehículos recreacionales.",
  "5530": "Servicio por horas.",
  "5590": "Otros tipos de alojamiento n.c.p.",
  "5611": "Expendio a la mesa de comidas preparadas.",
  "5612": "Expendio por autoservicio de comidas preparadas.",
  "5613": "Expendio de comidas preparadas en cafeterías.",
  "5619": "Otros tipos de expendio de comidas preparadas n.c.p.",
  "5621": "Catering para eventos.",
  "5629": "Actividades de otros servicios de comidas.",
  "5630": "Expendio de bebidas alcohólicas para el consumo dentro del establecimiento.",
  "5811": "Edición de libros.",
  "5812": "Edición de directorios y listas de correo.",
  "5813": "Edición de periódicos, revistas y otras publicaciones periódicas.",
  "5819": "Otros trabalhos de edición.",
  "5820": "Edición de programas de informática (software).",
  "5911": "Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión.",
  "5912": "Actividades de posproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión.",
  "5913": "Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión.",
  "5914": "Actividades de exhibición de películas cinematográficas y videos.",
  "5920": "Actividades de grabación de sonido y edición de música.",
  "6010": "Actividades de programación y transmisión en el servicio de radiodifusión sonora.",
  "6020": "Actividades de programación y transmisión de televisión.",
  "6110": "Actividades de telecomunicaciones alámbricas.",
  "6120": "Actividades de telecomunicaciones inalámbricas.",
  "6130": "Actividades de telecomunicación satelital.",
  "6190": "Otras actividades de telecomunicaciones.",
  "6201": "Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas).",
  "6202": "Actividades de consultoría informática y actividades de administración de instalaciones informáticas.",
  "6209": "Otras actividades de tecnologías de información y actividades de servicios informáticos.",
  "6311": "Procesamiento de datos, alojamiento (hosting) y actividades relacionadas.",
  "6312": "Portales web.",
  "6391": "Actividades de agencias de noticias.",
  "6399": "Otras actividades de servicio de información n.c.p.",
  "6411": "Banco Central.",
  "6412": "Bancos comerciales.",
  "6421": "Actividades de las corporaciones financieras.",
  "6422": "Actividades de las compañías de financiamiento.",
  "6423": "Banca de segundo piso.",
  "6424": "Actividades de las cooperativas financieras.",
  "6431": "Fideicomisos, fondos y entidades financieras similares.",
  "6432": "Fondos de cesantías.",
  "6491": "Leasing financiero (arrendamiento financiero).",
  "6492": "Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario.",
  "6493": "Actividades de compra de cartera o factoring.",
  "6494": "Otras actividades de distribución de fondos.",
  "6495": "Instituciones especiales oficiales.",
  "6496": "Capitalización.",
  "6499": "Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.",
  "6511": "Seguros generales.",
  "6512": "Seguros de vida.",
  "6513": "Reaseguros.",
  "6515": "Seguros de salud.",
  "6521": "Servicios de seguros sociales de salud.",
  "6522": "Servicios de seguros sociales de riesgos profesionales.",
  "6523": "Servicios de seguros sociales en riesgos familia.",
  "6531": "Régimen de prima media con prestación definida (RPM).",
  "6532": "Régimen de ahorro individual (RAI).",
  "6611": "Administración de mercados financieros.",
  "6612": "Corretaje de valores y de contratos de productos básicos.",
  "6613": "Otras actividades relacionadas con el mercado de valores.",
  "6614": "Actividades de las casas de cambio.",
  "6615": "Actividades de los profesionales de compra y venta de divisas.",
  "6619": "Otras actividades auxiliares de las actividades de servicios financieros n.c.p.",
  "6621": "Actividades de agentes y corredores de seguros.",
  "6629": "Evaluación de riesgos y daños, y otras actividades de servicios auxiliares.",
  "6630": "Actividades de administración de fondos.",
  "6810": "Actividades inmobiliarias realizadas con bienes propios o arrendados.",
  "6820": "Actividades inmobiliarias realizadas a cambio de una retribución o por contrata.",
  "6910": "Actividades jurídicas.",
  "6920": "Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria.",
  "7010": "Actividades de administración empresarial.",
  "7020": "Actividades de consultaría de gestión.",
  "7111": "Actividades de arquitectura.",
  "7112": "Actividades de ingeniería y otras actividades conexas de consultoría técnica.",
  "7120": "Ensayos y análisis técnicos.",
  "7210": "Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería.",
  "7220": "Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades.",
  "7310": "Publicidad.",
  "7320": "Estudios de mercado y realización de encuestas de opinión pública.",
  "7410": "Actividades especializadas de diseño.",
  "7420": "Actividades de fotografía.",
  "7490": "Otras actividades profesionales, científicas y técnicas n.c.p.",
  "7500": "Actividades veterinarias.",
  "7710": "Alquiler y arrendamiento de vehículos automotores.",
  "7721": "Alquiler y arrendamiento de equipo recreativo y deportivo.",
  "7722": "Alquiler de videos y discos.",
  "7729": "Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.",
  "7730": "Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.",
  "7740": "Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor.",
  "7810": "Actividades de agencias de empleo.",
  "7820": "Actividades de agencias de empleo temporal.",
  "7830": "Otras actividades de suministro de recurso humano.",
  "7911": "Actividades de las agencias de viaje.",
  "7912": "Actividades de operadores turísticos.",
  "7990": "Otros servicios de reserva y actividades relacionadas.",
  "8010": "Actividades de seguridad privada.",
  "8020": "Actividades de servicios de sistemas de seguridad.",
  "8030": "Actividades de detectives e investigadores privados.",
  "8110": "Actividades combinadas de apoyo a instalaciones.",
  "8121": "Limpieza general interior de edificios.",
  "8129": "Otras actividades de limpieza de edificios e instalaciones industriales.",
  "8130": "Actividades de paisajismo y servicios de mantenimiento conexos.",
  "8211": "Actividades combinadas de servicios administrativos de oficina.",
  "8219": "Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina.",
  "8220": "Actividades de centros de llamadas (Call center).",
  "8230": "Organización de convenciones y eventos comerciales.",
  "8291": "Actividades de agencias de cobranza y oficinas de calificación crediticia.",
  "8292": "Actividades de envase y empaque.",
  "8299": "Otras actividades de servicio de apoyo a las empresas n.c.p.",
  "8411": "Actividades legislativas de la administración pública.",
  "8412": "Actividades ejecutivas de la administración pública.",
  "8413": "Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social.",
  "8414": "Actividades reguladoras y facilitadoras de la actividad económica.",
  "8415": "Actividades de los otros órganos de control.",
  "8421": "Relaciones exteriores.",
  "8422": "Actividades de defensa.",
  "8423": "Orden público y actividades de seguridad.",
  "8424": "Administración de justicia.",
  "8430": "Actividades de planes de seguridad social de afiliación obligatoria.",
  "8511": "Educación de la primera infancia.",
  "8512": "Educación preescolar.",
  "8513": "Educación básica primaria.",
  "8521": "Educación básica secundaria.",
  "8522": "Educación media académica.",
  "8523": "Educación media técnica y de formación laboral.",
  "8530": "Establecimientos que combinan diferentes niveles de educación.",
  "8541": "Educación técnica profesional.",
  "8542": "Educación tecnológica.",
  "8543": "Educación de instituciones universitarias o de escuelas tecnológicas.",
  "8544": "Educación de universidades.",
  "8551": "Formación académica no formal.",
  "8552": "Enseñanza deportiva y recreativa.",
  "8553": "Enseñanza cultural.",
  "8559": "Otros tipos de educación n.c.p.",
  "8560": "Actividades de apoyo a la educación.",
  "8610": "Actividades de hospitales y clínicas, con internación.",
  "8621": "Actividades de la práctica médica, sin internación.",
  "8622": "Actividades de la práctica odontológica.",
  "8691": "Actividades de apoyo diagnóstico.",
  "8692": "Actividades de apoyo terapéutico.",
  "8699": "Otras actividades de atención de la salud humana.",
  "8710": "Actividades de atención residencial medicalizada de tipo general.",
  "8720": "Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas.",
  "8730": "Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas.",
  "8790": "Otras actividades de atención en instituciones con alojamiento.",
  "8810": "Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas.",
  "8891": "Actividades de guarderías para niños y niñas.",
  "8899": "Otras actividades de asistencia social sin alojamiento n.c.p.",
  "9001": "Creación literaria.",
  "9002": "Creación musical.",
  "9003": "Creación teatral.",
  "9004": "Creación audiovisual.",
  "9005": "Artes plásticas y visuales.",
  "9006": "Actividades teatrales.",
  "9007": "Actividades de espectáculos musicales en vivo.",
  "9008": "Otras actividades de espectáculos en vivo.",
  "9101": "Actividades de bibliotecas y archivos.",
  "9102": "Actividades y funcionamiento de museos, conservación de edificios y sitios históricos.",
  "9103": "Actividades de jardines botánicos, zoológicos y reservas naturales.",
  "9200": "Actividades de juegos de azar y apuestas.",
  "9311": "Gestión de instalaciones deportivas.",
  "9312": "Actividades de clubes deportivos",
  "9319": "Otras actividades deportivas.",
  "9321": "Actividades de parques de atracciones y parques temáticos.",
  "9329": "Otras actividades recreativas y de esparcimiento n.c.p.",
  "9411": "Actividades de asociaciones empresariales y de empleadores.",
  "9412": "Actividades de asociaciones profesionales.",
  "9420": "Actividades de sindicatos de empleados.",
  "9491": "Actividades de asociaciones religiosas.",
  "9492": "Actividades de asociaciones políticas.",
  "9499": "Actividades de otras asociaciones n.c.p.",
  "9511": "Mantenimiento y reparación de computadores y de equipo periférico.",
  "9512": "Mantenimiento y reparación de equipos de comunicación.",
  "9521": "Mantenimiento y reparación de aparatos electrónicos de consumo.",
  "9522": "Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería.",
  "9523": "Reparación de calzado y artículos de cuero.",
  "9524": "Reparación de muebles y accesorios para el hogar.",
  "9529": "Mantenimiento y reparación de otros efectos personales y enseres domésticos.",
  "9601": "Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel.",
  "9602": "Peluquería y otros tratamientos de belleza.",
  "9603": "Pompas fúnebres y actividades relacionadas.",
  "9609": "Otras actividades de servicios personales n.c.p.",
  "9700": "Actividades de los hogares individuales como empleadores de personal doméstico.",
  "9810": "Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio.",
  "9820": "Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio.",
  "9900": "Actividades de organizaciones y entidades extraterritoriales.",
  "10": "Asalariados.",
  "20": "Pensionados.",
  "81": "Personas Naturales sin Actividad Económica.",
  "82": "Personas Naturales Subsidiadas por Terceros.",
  "90": "Rentistas de Capital, solo para personas naturales.",
};

/** CIIU secundario + actividad para PDFs (matriz / formulario proveedores). */
export function actividadSecundariaDesdeMatrizProveedor(
  matriz:
    | { codigoCiiuSecundario?: string; actividadEconomicaSecundaria?: string }
    | undefined,
): { codigoCiiu: string; actividadEconomica: string } | undefined {
  if (!matriz) return undefined;
  const secC = matriz.codigoCiiuSecundario?.trim();
  const secA = matriz.actividadEconomicaSecundaria?.trim();
  if (!secC && !secA) return undefined;
  return {
    codigoCiiu: secC || "—",
    actividadEconomica: secA || (secC ? CIIU_ACTIVIDAD[secC] ?? "—" : "—"),
  };
}
